### ISSUE TITLE
Docs issue: Various hyperlinks not working

### ISSUE THREAD

**Issue by paulmccrady** [cloudyspells/PSRule.Rules.AzureDevOps#52]
# **📚 Documentation Issue Report**

## **Describe the bug**

When clicking on the link https://github.com/cloudyspells/PSRule.Rules.AzureDevOps/blob/main/CONTRIBUTING.md#code-of-conduct the user receives a Not Found page.

When clicking on any of the following links nothing happens (as the links reference missing markdown sections)

![Screenshot 2023-10-24 at 10 21 38](https://github.com/cloudyspells/PSRule.Rules.AzureDevOps/assets/30175621/0d749bf5-ea13-4c73-885e-b3f280f9a156)

When clicking on the rule hyperlinks in https://github.com/cloudyspells/PSRule.Rules.AzureDevOps/blob/main/docs/token-permissions.md user gets 404 page not found

---

### **To Reproduce Contributing (Not Found)**

1. From code tab click on CONTRIBUTING.md
2. Click on Code of Conduct link in table of contents
3. Click on PSRule.Rules.AzureDevOps Code of Conduct

### **To Reproduce Inactivity**

1. From code tab click on CONTRIBUTING.md
2. Click on Code of Conduct link in table of contents
3. Click on Styleguides, Commit Messages or Join the Project Team 

### **To Reproduce Rules Link (Not Found)**

1. From code tab click on docs/token-permissions.md
2. Click on a rule link in Token Scope for Rules section

---

### **Media prove**

<img width="761" alt="Screenshot 2023-10-24 at 10 16 03" src="https://github.com/cloudyspells/PSRule.Rules.AzureDevOps/assets/30175621/28800b28-aad6-4d28-b5d7-69dd424e0367">

---

## **Describe the solution you'd like**

Hyperlink corrected so the user does not see a Not Found page.
Sections for Styleguides, commit messages and join the project team added to documentation.

---

### **Additional context**

The link in the CONTRIBUTING.md markdown file needs a small amendment. 

The current link is:
https://github.com/cloudyspells/PSRule.Rules.AzureDevOpsblob/master/CODE_OF_CONDUCT.md

but this needs changing to:
https://github.com/cloudyspells/PSRule.Rules.AzureDevOps/blob/main/CODE_OF_CONDUCT.md

i.e. change branch from master to main

In Token Scope for Rules example link:

https://github.com/cloudyspells/PSRule.Rules.AzureDevOps/blob/main/docs/src/PSRule.Rules.AzureDevOps/en/Azure.DevOps.Tasks.VariableGroup.NoPlainTextSecrets.md

but this needs changing to:

https://github.com/cloudyspells/PSRule.Rules.AzureDevOps/blob/main/src/PSRule.Rules.AzureDevOps/en/Azure.DevOps.Tasks.VariableGroup.NoPlainTextSecrets.md

i.e. remove /docs from the link path

**Comment by paulmccrady** [comment]
Hey @webtonize I'd like to start contributing but feel need the styleguides, commit messages and join the project team links to read through before hand.

**Comment by webtonize** [comment]
Hi @paulmccrady , thanks so much for your contribution and I am happy to welcome you onboard as a contributor. I will look in to improving contribution guidelines, docs etc probably on thursday as that is the earliest opportunity to spend some serious time on this project again.
